discord:
  TOKEN: ${DISCORD_TOKEN}

bot:
  prefix: "/"

intents:
  messages: true
  message_content: true

modules:
  - cogs.builds
  - cogs.blacksmithing
  - cogs.synthesis
  - cogs.equipment
  - events
