name: Bot Discord Bot Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your Python version
        
    - name: Install discord.py
      run: python -m pip install -U discord.py
      
    - name: Run bot
      run: python bot.py  # Replace with your bot file name
      
    - name: Run bot continuously
      run: |
        while true; do
          python bot.py
          sleep 5
        done
